### ISSUE TITLE
TypeScript client example send-transactions-example failing

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-rosetta#258]
``` console
yarn send-transactions-example
yarn run v1.22.5
$ ts-node send-transaction-example.ts
[doRun] secretKey 41d9523b87b9bd89a4d07c9b957ae68a7472d8145d7956a692df1a8ad91957a2c117d9dd874447f47306f50a650f1e08bf4bec2cfcb2af91660f23f2db912977
[constructionDerive] Fetching an address for pub key c117d9dd874447f47306f50a650f1e08bf4bec2cfcb2af91660f23f2db912977
[constructionDerive] Retrieved address addr_test1vru64wlzn85v7fecg0mz33lh00wlggqtquvzzuhf6vusyes32jz9w
[waitForBalanceToBe] Funds found! 50000000 ADA
addr_test1vru64wlzn85v7fecg0mz33lh00wlggqtquvzzuhf6vusyes32jz9w
TypeError: Cannot read property 'publicKey' of undefined
    at /home/rhys/code/iohk/cardano-rosetta/examples/TypeScript/commons.ts:171:65
    at Array.map (<anonymous>)
    at Object.signPayloads (/home/rhys/code/iohk/cardano-rosetta/examples/TypeScript/commons.ts:169:12)
    at /home/rhys/code/iohk/cardano-rosetta/examples/TypeScript/send-transaction-example.ts:47:22
    at step (/home/rhys/code/iohk/cardano-rosetta/examples/TypeScript/send-transaction-example.ts:33:23)
    at Object.next (/home/rhys/code/iohk/cardano-rosetta/examples/TypeScript/send-transaction-example.ts:14:53)
    at fulfilled (/home/rhys/code/iohk/cardano-rosetta/examples/TypeScript/send-transaction-example.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Done in 1.10s.

```

**Comment by AlanVerbner** [comment]
@rhyslbw I don't think this is happening atm, can you please confirm?
