### ISSUE TITLE
submit transaction response error, but infact the transaction has been successfully submitted. version: 1.7.0

### ISSUE THREAD

**Issue by somereason** [input-output-hk/cardano-rosetta#464]
My request

```json
{
    "network_identifier": {
        "blockchain": "cardano",
        "network": "testnet"
    },
    "signed_transaction": "8279018a38346134303038313832353832303564636532623139663133363932323131313565653132633134616633356235346639363535326239333535343732346562646336336233616631373137373130303031383138323538316436306464613634313865373634616337373032343464616439373636656138383936646434646563343931616562316435316363316132643037316130356566633638303032316130303033306434303033316130336566313438306131303038313832353832306166386330623861623034336136633565356161313436363665313933333439623335306538313435326462343738333034346437303635326132343538363135383430333936323230396635663334316361613661333434663431343339633037343336353039336435366162363930636636636134646364373136643963666331393363376632663363323838636433653965613361313666646136393762613336626366323332373763626430316264366162363964613331623534303636306566356636a1696f7065726174696f6e60"
}
```

cardano-rosetta response 
```json
{
    "code": 5006,
    "message": "Error when sending the transaction",
    "retriable": true,
    "details": {
        "message": "Parse signed transaction error"
    }
}
```

but infact, the transaction has been submit to testnet. https://testnet.cardanoscan.io/transaction/607452ed1beaafd69df00cb3667dd393cea655a58686442c2d74914066486a20

when I checked the log of rosetta, I found this: 

```

[5ea2eecd:cardano.node.Mempool:Info:25853] [2022-03-29 09:45:07.26 UTC] fromList [("tx",Object (fromList [("txid",String "607452ed")])),("kind",String "TraceMempoolAddedTx"),("mempoolSize",Object (fromList [("bytes",Number 200.0),("numTxs",Number 1.0)]))]
{"level":30,"time":1648547107270,"pid":104,"hostname":"5ea2eecd794e","reqId":101996,"msg":"[submitTransaction] transaction successfully sent Transaction successfully submitted.","v":1}
{"level":30,"time":1648547107270,"pid":104,"hostname":"5ea2eecd794e","reqId":101996,"msg":"[constructionHash] About to get hash of signed transaction","v":1}
{"level":30,"time":1648547107270,"pid":104,"hostname":"5ea2eecd794e","reqId":101996,"msg":"[getHashOfSignedTransaction] About to hash signed transaction 84a400818258205dce2b19f1369221115ee12c14af35b54f96552b93554724ebdc63b3af17177100018182581d60dda6418e764ac770244dad9766ea8896dd4dec491aeb1d51cc1a2d071a05efc680021a00030d40031a03ef1480a10081825820af8c0b8ab043a6c5e5aa14666e193349b350e81452db4783044d70652a24586158403962209f5f341caa6a344f41439c074365093d56ab690cf6ca4dcd716d9cfc193c7f2f3c288cd3e9ea3a16fda697ba36bcf23277cbd01bd6ab69da31b540660ef5f6","v":1}
{"level":30,"time":1648547107270,"pid":104,"hostname":"5ea2eecd794e","reqId":101996,"msg":"[getHashOfSignedTransaction] About to parse transaction from signed transaction bytes","v":1}
{"level":50,"time":1648547107271,"pid":104,"hostname":"5ea2eecd794e","reqId":101996,"error":"Deserialization failed in Transaction.auxiliary_data because: Expected null, found other type","msg":"[getHashOfSignedTransaction] There was an error parsing signed transaction","v":1}
{"level":50,"time":1648547107271,"pid":104,"hostname":"5ea2eecd794e","reqId":101996,"code":5003,"retriable":false,"msg":"Parse signed transaction error","stack":"Error: Parse signed transaction error\n    at Object.exports.buildApiError (/cardano-rosetta-server/dist/src/server/utils/errors.js:118:56)\n    at Object.parseSignedTransactionError (/cardano-rosetta-server/dist/src/server/utils/errors.js:144:51)\n    at Object.getHashOfSignedTransaction (/cardano-rosetta-server/dist/src/server/services/cardano-services.js:233:41)\n    at /cardano-rosetta-server/dist/src/server/controllers/construction-controller.js:179:56\n    at Generator.next (<anonymous>)\n    at fulfilled (/cardano-rosetta-server/dist/src/server/controllers/construction-controller.js:5:58)","type":"Error","v":1}
{"level":50,"time":1648547107272,"pid":104,"hostname":"5ea2eecd794e","reqId":101996,"code":5006,"retriable":true,"details":{"message":"Parse signed transaction error"},"msg":"[errorHandler] An error ocurred and will be sent as response","stack":"Error: Error when sending the transaction\n    at Object.exports.buildApiError (/cardano-rosetta-server/dist/src/server/utils/errors.js:118:56)\n    at Object.sendTransactionError (/cardano-rosetta-server/dist/src/server/utils/errors.js:153:51)\n    at /cardano-rosetta-server/dist/src/server/controllers/construction-controller.js:187:56","type":"Error","v":1}
```

**Comment by james-iohk** [comment]
Hi @somereason thanks for raising. Is this reproducible? It would be useful to have the steps you took to construct the transaction.

**Comment by somereason** [comment]
> 

```java
   //cardano client lib
    @Test
    void calcTxHash() throws Exception {
        BigInteger fee = BigInteger.valueOf(200000);
        BigInteger inputAmount = BigInteger.valueOf(99600000);
        var bodyBuilder = new TransactionBody.TransactionBodyBuilder()
                .ttl(66000000)
                .inputs(List.of(new TransactionInput.TransactionInputBuilder()
                        .transactionId("607452ed1beaafd69df00cb3667dd393cea655a58686442c2d74914066486a20")
                        .index(0)
                        .build()))
                .outputs(List.of(new TransactionOutput.TransactionOutputBuilder()
                        .address(address)
                        .value(Value.builder()
                                .coin(inputAmount.subtract(fee))
                                .build())
                        .build()))
                .fee(fee);
        Transaction tx = Transaction.builder()
                .body(bodyBuilder.build())
                .auxiliaryData(AuxiliaryData.builder()
                        .metadata(new CBORMetadata().put(BigInteger.valueOf(1924), "hello world"))
                        .build())
                .build();
        tx = account.sign(tx);
        System.out.println(tx.getBody().getHash());
        Assertions.assertTrue(tx.getBody().getHash().equals("ed274c6e445d3b173956d788bd33acfe1fcafa18d7a2b9c0d89c2ffd465888b6"));
        System.out.println(HexUtil.encodeHexString(getRosettaBytes(tx.serializeToHex())));
    }

    public static byte[] getRosettaBytes(String signedTxn) throws CborException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        new CborEncoder(baos).encode(new CborBuilder()
                .addArray()
                .add(signedTxn)
                .addMap()
                .addKey("operation")
                .value("")
                .end()
                .end()
                .build());
        return baos.toByteArray();
    }

```

note: getRosettaBytes works fine under cardano-clinet-lib version 0.1.5 and cardano-rosetta 1.5.0, but now I'm using cardano-clinet-lib version 0.2.0-beta2

**Comment by james-iohk** [comment]
I couldn't say exactly the cause here because Rosetta is intended to be used with the construction workflow, see [Flow of Operations](https://www.rosetta-api.org/docs/construction_api_introduction.html#flow-of-operations). Perhaps this issue is related to deserialising a transaction with custom metadata.

**Comment by somereason** [comment]
> I couldn't say exactly the cause here because Rosetta is intended to be used with the construction workflow, see [Flow of Operations](https://www.rosetta-api.org/docs/construction_api_introduction.html#flow-of-operations). Perhaps this issue is related to deserialising a transaction with custom metadata.

but this transaction has broadcasted. so it seems the hex is legal.
